name: $(version)$(Rev:.r)
variables:
  version: 0.1
  nugetVersion: 4.9.2
  dotNetSdkVersion: 2.2.101
  reportGenerator_Version: 4.0.4
  buildConfiguration: "Release"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

trigger:
- master

pr:
- master

pool:
  name: "Hosted VS2017"

steps:
- task: NuGetToolInstaller@0
  displayName: "Install NuGet Client"
  inputs:
    versionSpec: $(nugetVersion)

- task: DotNetCoreInstaller@0
  displayName: "Install .NET Core SDK"
  inputs:
    packageType: 'sdk'
    version: $(dotNetSdkVersion)

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: --configuration $(buildConfiguration) --no-restore -p:Version=$(Build.BuildNumber)

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: '**/*.sln'
    arguments: --configuration $(buildConfiguration) --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\Coverage\ /p:Exclude="[AspNetCore.Testing.Site]*"

- script: >-
    dotnet tool install dotnet-reportgenerator-globaltool 
    --global 
    --version $(reportGenerator_Version)
  displayName: "Install code coverage report generator tool"

- script: >-
    reportgenerator 
    "-reports:$(Build.SourcesDirectory)\Coverage\*.xml" 
    "-targetdir:$(Build.SourcesDirectory)\Coverage\Html" 
    "-reporttypes:Cobertura;HtmlInline_AzurePipelines;Badges"
  displayName: Generate code coverage report

- task: DotNetCoreCLI@2
  displayName: "Pack"
  inputs:
    command: 'pack'
    configuration: 'release'
    projects: '**/AspNetCore.Testing.RoleHandler.csproj'
    arguments: --configuration $(buildConfiguration) --no-restore

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(Build.SourcesDirectory)\coverage\.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\coverage\html

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'packages' 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))